on: [push]

jobs:
  my-jobs:
    run-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v2
    - name: run the action
     id: hello
     uses: ./
     with: 
      myInput: 'chimezie'
    - name: output
      run: |
      echo ${{steps.hello.outputs.memory}}
      echo 'total memory output'
      
